---
- name: GoKEV.lab-provision
  version: master
  src: https://github.com/GoKEV/GoKEV-lab-provision.git

- name: GoKEV.lab-installtower
  version: master
  src: https://github.com/GoKEV/GoKEV-lab-installtower.git

- name: GoKEV.lab-configtower
  version: master
  src: https://github.com/GoKEV/GoKEV-lab-configtower.git

- name: GoKEV.lab-deck
  version: master
  src: https://github.com/GoKEV/GoKEV-lab-deck.git

